import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import Carousel from "react-bootstrap/Carousel";
import Container from "react-bootstrap/Container";

export default function Home() {
  
  const imagesSlide = [
    {
      id: 1,
      src: "/images/college/1.jpeg",
    },
    {
      id: 2,
      src: "/images/college/2.jpeg",
    },
    {
      id: 3,
      src: "/images/college/3.jpeg",
    },
    {
      id: 4,
      src: "/images/college/4.jpeg",
    },
  ];
  return (
    <div className={styles.container}>
      <Head>
        <title>Sridisha Tech Institute</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{overflowY:"auto"}}>
        <Container className="d-flex mt-3 p-4 h-100 w-100 bg-gradient bg-warning">
          <Container >
            <Carousel className="d-block h-100 w-100">
              {imagesSlide.map((x) => {
                return (
                  <Carousel.Item className="h-50">
                    <img style={{ width: "100%" }} src={x.src} alt="" />
                  </Carousel.Item>
                );
              })}
            </Carousel>
          </Container>
          <Container className="d-flex flex-column">
            <h4>
              About Us:
            </h4>
            <p>
              Inspired by the ideals of APJ Abdul Kalam, Sridisha College
              of Technology was established, in 1958, to meet the diverse
              educational needs of the Capital of independent India. The Gujarat
              Education Society which established the college manages it through
              elected representatives in the Governing Body. The Governing Body
              lays down the direction, the policies and the guidelines for the
              college and monitors its performance on an on going basis. The
              President and the Hon. Secretary of the Society, as the Executive
              arms of the Society, are responsible for the overall control of
              the management of the college. The day-to-day academic and
              administrative management of the college is the responsibility of
              the Director and the CEO.
            </p>
          </Container>
        </Container>
      </main>
    </div>
  );
}
